from nltk.translate.bleu_score import sentence_bleu
from nltk.tokenize import word_tokenize

def calculate_bleu_score(reference, candidate):
    """
    Calculate the BLEU score for a given reference and candidate text.
    
    :param reference: str, the reference text
    :param candidate: str, the candidate text generated by the model
    :return: float, the BLEU score
    """
    reference_tokens = [word_tokenize(reference.lower())]
    candidate_tokens = word_tokenize(candidate.lower())
    
    return sentence_bleu(reference_tokens, candidate_tokens)